# Generated by Django 2.0.3 on 2018-04-01 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20180401_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.Pessoa')),
                ('curriculo', models.CharField(max_length=100)),
                ('artigos', models.ManyToManyField(to='evento.ArtigoCientifico')),
            ],
            bases=('evento.pessoa',),
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('eventos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.Eventos')),
                ('issn', models.CharField(max_length=100)),
            ],
            bases=('evento.eventos',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.Pessoa')),
                ('cnpj', models.CharField(max_length=100)),
                ('razaoSocial', models.CharField(max_length=100)),
            ],
            bases=('evento.pessoa',),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='autores',
            field=models.ManyToManyField(to='evento.Autor'),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evento.EventoCientifico'),
        ),
    ]
